/mob/Stat()
	. = ..()
	if(statpanel("MC"))
		var/turf/T = get_turf(client.eye)
		stat("Location:", COORD(T))
		stat("CPU:", "[world.cpu]")
		stat("Instances:", "[num2text(world.contents.len, 10)]")
		GLOB.stat_entry()
		stat(null)
		if(Master)
			Master.stat_entry()
		else
			stat("Master Controller:", "ERROR")
		if(Failsafe)
			Failsafe.stat_entry()
		else
			stat("Failsafe Controller:", "ERROR")
		if(Master)
			stat(null)
			for(var/datum/controller/subsystem/SS in Master.subsystems)
				SS.stat_entry()